#!/usr/bin/env bash
set -Eeo pipefail
shopt -s globstar
. commands.sh

function version() {
  export BRANCH=${CIRCLE_BRANCH-$(git rev-parse --abbrev-ref HEAD)}
  export BUILD_NUMBER=${CIRCLE_BUILD_NUM-$(date -u +"%Y%m%d%H%M%S")}
  export REVISIONS=$(git rev-list --count ${BRANCH})
  export VERSION=0.${REVISIONS}.${BUILD_NUMBER}

  echo version: ${VERSION}
}

function tag() {
  version

  git config --global user.name "Server"
  git config --global user.email "server@bodar.com"
  git tag -a ${VERSION} -m "Release ${VERSION}"
  git push origin ${VERSION}
}

function clean() {
  rm -rf artifacts
  bun install
}

function check() {
  bun run --bun tsc --noEmit
}

function test() {
  bun test "$@"
}

function coverage() {
  test --coverage
}

function dev() {
  test --watch
}

function build() {
  check
  test
}

function ci() {
  check
  coverage
  tag
}

clean

command="${1-build}"
set +e; shift; set -Eeo pipefail;
$command "$@"
